//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProjectCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public int idFilm { get; set; }
        public int idHall { get; set; }
        public int IdCinema { get; set; }
        public int Price { get; set; }
        public System.DateTime sessionTime { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Halls Halls { get; set; }
        public virtual Cinemas Cinemas { get; set; }
    }
}
